//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.4927
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("QuizDB", "FK_Answer_Question", "Question", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(QuizLibrary.Data.QuestionEntity), "Answer", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(QuizLibrary.Data.AnswerEntity))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("QuizDB", "FK_Question_Category", "Category", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(QuizLibrary.Data.CategoryEntity), "Question", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(QuizLibrary.Data.QuestionEntity))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("QuizDB", "FK_Score_Category", "Category", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(QuizLibrary.Data.CategoryEntity), "Score", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(QuizLibrary.Data.ScoreEntity))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("QuizDB", "FK_Score_User", "User", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(QuizLibrary.Data.UserEntity), "Score", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(QuizLibrary.Data.ScoreEntity))]

// Nombre de archivo original:
// Fecha de generación: 12/04/2010 13:38:25
namespace QuizLibrary.Data
{
    
    /// <summary>
    /// No hay ningún comentario para DataBase en el esquema.
    /// </summary>
    public partial class DataBase : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Inicializa un nuevo objeto DataBase usando la cadena de conexión encontrada en la sección 'DataBase' del archivo de configuración de la aplicación.
        /// </summary>
        public DataBase() : 
                base("name=DataBase", "DataBase")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Inicializar un nuevo objeto DataBase.
        /// </summary>
        public DataBase(string connectionString) : 
                base(connectionString, "DataBase")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Inicializar un nuevo objeto DataBase.
        /// </summary>
        public DataBase(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "DataBase")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// No hay ningún comentario para AnswerEntities en el esquema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<AnswerEntity> AnswerEntities
        {
            get
            {
                if ((this._AnswerEntities == null))
                {
                    this._AnswerEntities = base.CreateQuery<AnswerEntity>("[AnswerEntities]");
                }
                return this._AnswerEntities;
            }
        }
        private global::System.Data.Objects.ObjectQuery<AnswerEntity> _AnswerEntities;
        /// <summary>
        /// No hay ningún comentario para CategoryEntities en el esquema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<CategoryEntity> CategoryEntities
        {
            get
            {
                if ((this._CategoryEntities == null))
                {
                    this._CategoryEntities = base.CreateQuery<CategoryEntity>("[CategoryEntities]");
                }
                return this._CategoryEntities;
            }
        }
        private global::System.Data.Objects.ObjectQuery<CategoryEntity> _CategoryEntities;
        /// <summary>
        /// No hay ningún comentario para QuestionEntities en el esquema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<QuestionEntity> QuestionEntities
        {
            get
            {
                if ((this._QuestionEntities == null))
                {
                    this._QuestionEntities = base.CreateQuery<QuestionEntity>("[QuestionEntities]");
                }
                return this._QuestionEntities;
            }
        }
        private global::System.Data.Objects.ObjectQuery<QuestionEntity> _QuestionEntities;
        /// <summary>
        /// No hay ningún comentario para ScoreEntities en el esquema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ScoreEntity> ScoreEntities
        {
            get
            {
                if ((this._ScoreEntities == null))
                {
                    this._ScoreEntities = base.CreateQuery<ScoreEntity>("[ScoreEntities]");
                }
                return this._ScoreEntities;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ScoreEntity> _ScoreEntities;
        /// <summary>
        /// No hay ningún comentario para UserEntities en el esquema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<UserEntity> UserEntities
        {
            get
            {
                if ((this._UserEntities == null))
                {
                    this._UserEntities = base.CreateQuery<UserEntity>("[UserEntities]");
                }
                return this._UserEntities;
            }
        }
        private global::System.Data.Objects.ObjectQuery<UserEntity> _UserEntities;
        /// <summary>
        /// No hay ningún comentario para AnswerEntities en el esquema.
        /// </summary>
        public void AddToAnswerEntities(AnswerEntity answerEntity)
        {
            base.AddObject("AnswerEntities", answerEntity);
        }
        /// <summary>
        /// No hay ningún comentario para CategoryEntities en el esquema.
        /// </summary>
        public void AddToCategoryEntities(CategoryEntity categoryEntity)
        {
            base.AddObject("CategoryEntities", categoryEntity);
        }
        /// <summary>
        /// No hay ningún comentario para QuestionEntities en el esquema.
        /// </summary>
        public void AddToQuestionEntities(QuestionEntity questionEntity)
        {
            base.AddObject("QuestionEntities", questionEntity);
        }
        /// <summary>
        /// No hay ningún comentario para ScoreEntities en el esquema.
        /// </summary>
        public void AddToScoreEntities(ScoreEntity scoreEntity)
        {
            base.AddObject("ScoreEntities", scoreEntity);
        }
        /// <summary>
        /// No hay ningún comentario para UserEntities en el esquema.
        /// </summary>
        public void AddToUserEntities(UserEntity userEntity)
        {
            base.AddObject("UserEntities", userEntity);
        }
    }
    /// <summary>
    /// No hay ningún comentario para QuizDB.AnswerEntity en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// IdAnswer
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="QuizDB", Name="AnswerEntity")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class AnswerEntity : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto AnswerEntity.
        /// </summary>
        /// <param name="idAnswer">Valor inicial de IdAnswer.</param>
        /// <param name="answer">Valor inicial de Answer.</param>
        /// <param name="correct">Valor inicial de Correct.</param>
        public static AnswerEntity CreateAnswerEntity(int idAnswer, string answer, bool correct)
        {
            AnswerEntity answerEntity = new AnswerEntity();
            answerEntity.IdAnswer = idAnswer;
            answerEntity.Answer = answer;
            answerEntity.Correct = correct;
            return answerEntity;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad IdAnswer en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAnswer
        {
            get
            {
                return this._IdAnswer;
            }
            set
            {
                this.OnIdAnswerChanging(value);
                this.ReportPropertyChanging("IdAnswer");
                this._IdAnswer = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdAnswer");
                this.OnIdAnswerChanged();
            }
        }
        private int _IdAnswer;
        partial void OnIdAnswerChanging(int value);
        partial void OnIdAnswerChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Answer en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer
        {
            get
            {
                return this._Answer;
            }
            set
            {
                this.OnAnswerChanging(value);
                this.ReportPropertyChanging("Answer");
                this._Answer = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Answer");
                this.OnAnswerChanged();
            }
        }
        private string _Answer;
        partial void OnAnswerChanging(string value);
        partial void OnAnswerChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Correct en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool Correct
        {
            get
            {
                return this._Correct;
            }
            set
            {
                this.OnCorrectChanging(value);
                this.ReportPropertyChanging("Correct");
                this._Correct = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Correct");
                this.OnCorrectChanged();
            }
        }
        private bool _Correct;
        partial void OnCorrectChanging(bool value);
        partial void OnCorrectChanged();
        /// <summary>
        /// No hay ningún comentario para Question en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("QuizDB", "FK_Answer_Question", "Question")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public QuestionEntity Question
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<QuestionEntity>("QuizDB.FK_Answer_Question", "Question").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<QuestionEntity>("QuizDB.FK_Answer_Question", "Question").Value = value;
            }
        }
        /// <summary>
        /// No hay ningún comentario para Question en el esquema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<QuestionEntity> QuestionReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<QuestionEntity>("QuizDB.FK_Answer_Question", "Question");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<QuestionEntity>("QuizDB.FK_Answer_Question", "Question", value);
                }
            }
        }
    }
    /// <summary>
    /// No hay ningún comentario para QuizDB.CategoryEntity en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// IdCategory
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="QuizDB", Name="CategoryEntity")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class CategoryEntity : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto CategoryEntity.
        /// </summary>
        /// <param name="idCategory">Valor inicial de IdCategory.</param>
        /// <param name="category">Valor inicial de Category.</param>
        public static CategoryEntity CreateCategoryEntity(int idCategory, string category)
        {
            CategoryEntity categoryEntity = new CategoryEntity();
            categoryEntity.IdCategory = idCategory;
            categoryEntity.Category = category;
            return categoryEntity;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad IdCategory en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCategory
        {
            get
            {
                return this._IdCategory;
            }
            set
            {
                this.OnIdCategoryChanging(value);
                this.ReportPropertyChanging("IdCategory");
                this._IdCategory = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdCategory");
                this.OnIdCategoryChanged();
            }
        }
        private int _IdCategory;
        partial void OnIdCategoryChanging(int value);
        partial void OnIdCategoryChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Category en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Category
        {
            get
            {
                return this._Category;
            }
            set
            {
                this.OnCategoryChanging(value);
                this.ReportPropertyChanging("Category");
                this._Category = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Category");
                this.OnCategoryChanged();
            }
        }
        private string _Category;
        partial void OnCategoryChanging(string value);
        partial void OnCategoryChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Description en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// No hay ningún comentario para Questions en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("QuizDB", "FK_Question_Category", "Question")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<QuestionEntity> Questions
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<QuestionEntity>("QuizDB.FK_Question_Category", "Question");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<QuestionEntity>("QuizDB.FK_Question_Category", "Question", value);
                }
            }
        }
        /// <summary>
        /// No hay ningún comentario para Scores en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("QuizDB", "FK_Score_Category", "Score")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ScoreEntity> Scores
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ScoreEntity>("QuizDB.FK_Score_Category", "Score");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ScoreEntity>("QuizDB.FK_Score_Category", "Score", value);
                }
            }
        }
    }
    /// <summary>
    /// No hay ningún comentario para QuizDB.QuestionEntity en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// IdQuestion
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="QuizDB", Name="QuestionEntity")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class QuestionEntity : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto QuestionEntity.
        /// </summary>
        /// <param name="idQuestion">Valor inicial de IdQuestion.</param>
        /// <param name="question">Valor inicial de Question.</param>
        /// <param name="difficulty">Valor inicial de Difficulty.</param>
        public static QuestionEntity CreateQuestionEntity(int idQuestion, string question, byte difficulty)
        {
            QuestionEntity questionEntity = new QuestionEntity();
            questionEntity.IdQuestion = idQuestion;
            questionEntity.Question = question;
            questionEntity.Difficulty = difficulty;
            return questionEntity;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad IdQuestion en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IdQuestion
        {
            get
            {
                return this._IdQuestion;
            }
            set
            {
                this.OnIdQuestionChanging(value);
                this.ReportPropertyChanging("IdQuestion");
                this._IdQuestion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdQuestion");
                this.OnIdQuestionChanged();
            }
        }
        private int _IdQuestion;
        partial void OnIdQuestionChanging(int value);
        partial void OnIdQuestionChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Question en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Question
        {
            get
            {
                return this._Question;
            }
            set
            {
                this.OnQuestionChanging(value);
                this.ReportPropertyChanging("Question");
                this._Question = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Question");
                this.OnQuestionChanged();
            }
        }
        private string _Question;
        partial void OnQuestionChanging(string value);
        partial void OnQuestionChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Difficulty en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte Difficulty
        {
            get
            {
                return this._Difficulty;
            }
            set
            {
                this.OnDifficultyChanging(value);
                this.ReportPropertyChanging("Difficulty");
                this._Difficulty = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Difficulty");
                this.OnDifficultyChanged();
            }
        }
        private byte _Difficulty;
        partial void OnDifficultyChanging(byte value);
        partial void OnDifficultyChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Image en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Image
        {
            get
            {
                return this._Image;
            }
            set
            {
                this.OnImageChanging(value);
                this.ReportPropertyChanging("Image");
                this._Image = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Image");
                this.OnImageChanged();
            }
        }
        private string _Image;
        partial void OnImageChanging(string value);
        partial void OnImageChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Sound en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Sound
        {
            get
            {
                return this._Sound;
            }
            set
            {
                this.OnSoundChanging(value);
                this.ReportPropertyChanging("Sound");
                this._Sound = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Sound");
                this.OnSoundChanged();
            }
        }
        private string _Sound;
        partial void OnSoundChanging(string value);
        partial void OnSoundChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad CreateBy en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateBy
        {
            get
            {
                return this._CreateBy;
            }
            set
            {
                this.OnCreateByChanging(value);
                this.ReportPropertyChanging("CreateBy");
                this._CreateBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CreateBy");
                this.OnCreateByChanged();
            }
        }
        private string _CreateBy;
        partial void OnCreateByChanging(string value);
        partial void OnCreateByChanged();
        /// <summary>
        /// No hay ningún comentario para Answers en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("QuizDB", "FK_Answer_Question", "Answer")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<AnswerEntity> Answers
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<AnswerEntity>("QuizDB.FK_Answer_Question", "Answer");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<AnswerEntity>("QuizDB.FK_Answer_Question", "Answer", value);
                }
            }
        }
        /// <summary>
        /// No hay ningún comentario para Category en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("QuizDB", "FK_Question_Category", "Category")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public CategoryEntity Category
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CategoryEntity>("QuizDB.FK_Question_Category", "Category").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CategoryEntity>("QuizDB.FK_Question_Category", "Category").Value = value;
            }
        }
        /// <summary>
        /// No hay ningún comentario para Category en el esquema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<CategoryEntity> CategoryReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CategoryEntity>("QuizDB.FK_Question_Category", "Category");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<CategoryEntity>("QuizDB.FK_Question_Category", "Category", value);
                }
            }
        }
    }
    /// <summary>
    /// No hay ningún comentario para QuizDB.ScoreEntity en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// IdUser
    /// IdCategory
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="QuizDB", Name="ScoreEntity")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ScoreEntity : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto ScoreEntity.
        /// </summary>
        /// <param name="idUser">Valor inicial de IdUser.</param>
        /// <param name="idCategory">Valor inicial de IdCategory.</param>
        /// <param name="correct">Valor inicial de Correct.</param>
        /// <param name="total">Valor inicial de Total.</param>
        public static ScoreEntity CreateScoreEntity(int idUser, int idCategory, int correct, int total)
        {
            ScoreEntity scoreEntity = new ScoreEntity();
            scoreEntity.IdUser = idUser;
            scoreEntity.IdCategory = idCategory;
            scoreEntity.Correct = correct;
            scoreEntity.Total = total;
            return scoreEntity;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad IdUser en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUser
        {
            get
            {
                return this._IdUser;
            }
            set
            {
                this.OnIdUserChanging(value);
                this.ReportPropertyChanging("IdUser");
                this._IdUser = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdUser");
                this.OnIdUserChanged();
            }
        }
        private int _IdUser;
        partial void OnIdUserChanging(int value);
        partial void OnIdUserChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad IdCategory en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCategory
        {
            get
            {
                return this._IdCategory;
            }
            set
            {
                this.OnIdCategoryChanging(value);
                this.ReportPropertyChanging("IdCategory");
                this._IdCategory = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdCategory");
                this.OnIdCategoryChanged();
            }
        }
        private int _IdCategory;
        partial void OnIdCategoryChanging(int value);
        partial void OnIdCategoryChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Correct en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Correct
        {
            get
            {
                return this._Correct;
            }
            set
            {
                this.OnCorrectChanging(value);
                this.ReportPropertyChanging("Correct");
                this._Correct = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Correct");
                this.OnCorrectChanged();
            }
        }
        private int _Correct;
        partial void OnCorrectChanging(int value);
        partial void OnCorrectChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Total en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Total
        {
            get
            {
                return this._Total;
            }
            set
            {
                this.OnTotalChanging(value);
                this.ReportPropertyChanging("Total");
                this._Total = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Total");
                this.OnTotalChanged();
            }
        }
        private int _Total;
        partial void OnTotalChanging(int value);
        partial void OnTotalChanged();
        /// <summary>
        /// No hay ningún comentario para Category en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("QuizDB", "FK_Score_Category", "Category")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public CategoryEntity Category
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CategoryEntity>("QuizDB.FK_Score_Category", "Category").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CategoryEntity>("QuizDB.FK_Score_Category", "Category").Value = value;
            }
        }
        /// <summary>
        /// No hay ningún comentario para Category en el esquema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<CategoryEntity> CategoryReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CategoryEntity>("QuizDB.FK_Score_Category", "Category");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<CategoryEntity>("QuizDB.FK_Score_Category", "Category", value);
                }
            }
        }
        /// <summary>
        /// No hay ningún comentario para User en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("QuizDB", "FK_Score_User", "User")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public UserEntity User
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<UserEntity>("QuizDB.FK_Score_User", "User").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<UserEntity>("QuizDB.FK_Score_User", "User").Value = value;
            }
        }
        /// <summary>
        /// No hay ningún comentario para User en el esquema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<UserEntity> UserReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<UserEntity>("QuizDB.FK_Score_User", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<UserEntity>("QuizDB.FK_Score_User", "User", value);
                }
            }
        }
    }
    /// <summary>
    /// No hay ningún comentario para QuizDB.UserEntity en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// IdUser
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="QuizDB", Name="UserEntity")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class UserEntity : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto UserEntity.
        /// </summary>
        /// <param name="idUser">Valor inicial de IdUser.</param>
        /// <param name="name">Valor inicial de Name.</param>
        /// <param name="since">Valor inicial de Since.</param>
        public static UserEntity CreateUserEntity(int idUser, string name, global::System.DateTime since)
        {
            UserEntity userEntity = new UserEntity();
            userEntity.IdUser = idUser;
            userEntity.Name = name;
            userEntity.Since = since;
            return userEntity;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad IdUser en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUser
        {
            get
            {
                return this._IdUser;
            }
            set
            {
                this.OnIdUserChanging(value);
                this.ReportPropertyChanging("IdUser");
                this._IdUser = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdUser");
                this.OnIdUserChanged();
            }
        }
        private int _IdUser;
        partial void OnIdUserChanging(int value);
        partial void OnIdUserChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Name en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Birthday en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> Birthday
        {
            get
            {
                return this._Birthday;
            }
            set
            {
                this.OnBirthdayChanging(value);
                this.ReportPropertyChanging("Birthday");
                this._Birthday = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Birthday");
                this.OnBirthdayChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _Birthday;
        partial void OnBirthdayChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnBirthdayChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Image en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Image
        {
            get
            {
                return this._Image;
            }
            set
            {
                this.OnImageChanging(value);
                this.ReportPropertyChanging("Image");
                this._Image = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Image");
                this.OnImageChanged();
            }
        }
        private string _Image;
        partial void OnImageChanging(string value);
        partial void OnImageChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad AboutMe en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string AboutMe
        {
            get
            {
                return this._AboutMe;
            }
            set
            {
                this.OnAboutMeChanging(value);
                this.ReportPropertyChanging("AboutMe");
                this._AboutMe = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("AboutMe");
                this.OnAboutMeChanged();
            }
        }
        private string _AboutMe;
        partial void OnAboutMeChanging(string value);
        partial void OnAboutMeChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Since en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime Since
        {
            get
            {
                return this._Since;
            }
            set
            {
                this.OnSinceChanging(value);
                this.ReportPropertyChanging("Since");
                this._Since = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Since");
                this.OnSinceChanged();
            }
        }
        private global::System.DateTime _Since;
        partial void OnSinceChanging(global::System.DateTime value);
        partial void OnSinceChanged();
        /// <summary>
        /// No hay ningún comentario para Scores en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("QuizDB", "FK_Score_User", "Score")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ScoreEntity> Scores
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ScoreEntity>("QuizDB.FK_Score_User", "Score");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ScoreEntity>("QuizDB.FK_Score_User", "Score", value);
                }
            }
        }
    }
}
